### ISSUE TITLE
Change project type to modern style

### ISSUE THREAD

**Issue by Pegoth** [Dealman/BannerlordModTemplate#4]
The new csproj is much more readable and works better (directory based, so if you copy new files into the project directory they are visible in the VS).

You can check how I did it here: https://github.com/Pegoth/UniversalClose/

**Comment by Dealman** [comment]
I assume you're referring to using Targets and replacing `$(GameDirectory)` with the path to Bannerlord? I mean all it would essentially achieve is just me replacing `$bannerlordassemblies$` with `$(GameDirectory)`...?

Or are you referring to something else that makes it more readable?

**Comment by Pegoth** [comment]
> I assume you're referring to using Targets and replacing `$(GameDirectory)` with the path to Bannerlord? I mean all it would essentially achieve is just me replacing `$bannerlordassemblies$` with `$(GameDirectory)`...?
> 
> Or are you referring to something else that makes it more readable?

Open my UniversalClose.csproj and your BannerlordModTemplate.csproj.

Mine starts with:
`<Project Sdk="Microsoft.NET.Sdk">`

Yours starts with:
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
```

This means yours are the old VS standard, mine is the new .NET Core standard, but later I set it to use the full framework instead with
`<TargetFramework>net472</TargetFramework>`

Overall the new standard uses much less code for the same thing (less clutter, more readable).

Edit: It's not a big thing, it's just that the new standard is easier to work with.

**Comment by Dealman** [comment]
Ah I see what you mean, will look into updating this for the next milestone since I'll be refactoring the whole thing. Thanks for the suggestion! :)

**Comment by Dealman** [comment]
I've been working on this for the refactor but sadly it doesn't seem like it supports project templates. There's so many weird workarounds I have to do for it to work.

For example there's no way to generate a launchSettings.json file via a project template _(that I know of at least)_ so I've had to do that manually.

I've managed to work around most of the issues but there's 2 issues left which I simply can't figure out. I might upload it as a separate branch to investigate later.

One is that `<Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />` causes issues when trying to build the mod because .NET SDK seems to try and import it again. But this is needed in the template for it to import assemblies and such properly.

And the other is that `project.assets.json` won't be generated at all, thus resulting in the mod being unable to build.

But for now I'll drop this as it's just taking up too much time for what is otherwise essentially done.

**Comment by Dealman** [comment]
Ran into some issues with Git but think I've sorted it out now.

There's now a separate branch for this, I will be cleaning up the master branch and revert it to the old format.

If you wanna have a go at fixing the last few issues you're more than welcome, I might try and tackle them again later but for now I'll be focusing on the master branch.

Feel free to use this issue as a topic if you wanna add some information or something! :)
